export const ListsOfData = [{
    id: 1,
    Name: "Jasmeen",
    Age: 32,
    RequestedAccess: "jira",
    RequestedAccessName: "JIRA",
    ApprovedBy: "Jatin",
    markCompleted: false,
},
{
    id: 2,
    Name: "Hridaye",
    Age: 32,
    RequestedAccess: "confluence",
    RequestedAccessName: "Confluence",
    ApprovedBy: "Jatin",
    markCompleted: true,
},
{
    id: 3,
    Name: "Hanaaya",
    Age: 32,
    RequestedAccess: "payadvice",
    RequestedAccessName: "Pay Advice",
    ApprovedBy: "Mark",
    markCompleted: false,
},
{
    id: 4,
    Name: "Scott",
    Age: 34,
    RequestedAccess: "jira",
    RequestedAccessName: "JIRA",
    ApprovedBy: "Mark",
    markCompleted: false,
}];